id: PC8AF7772
initial_creation_type: ocr
source_metadata:
  volumes:
    f6e709d89b904718b143448fed561640:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
