id: DD7B8AA3D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-23T08:33:26+00:00'
last_modified: '2022-05-30T06:44:13.242952+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    08bd:
      image_group_id: I1PD95846
      title: ཨེ་ཀ་ནཱ་ཐའི་དོན་འགྲེལ།
      total_pages: 1539
      order: 1
      base_file: 08bd.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
